name: Deploy jasonpyau.com on Git push

on:
  push:
    branches:
      - main
  workflow_dispatch:
          
jobs:
  deploy:
  
    runs-on: self-hosted
    
    steps:
      - name: Ensure permissions allow for the removal of existing files in the runner working directory
        run: |
            sudo chown -R $USER:$USER .
      - name: Checkout files
        uses: actions/checkout@v4
      - name: Copy files to desired directory and set file permissions
        env:
          TARGET_FOLDER: ${{ secrets.TARGET_FOLDER }}
        run: |
            sudo rsync -a . "$TARGET_FOLDER"
            sudo chown -R $USER:$USER "$TARGET_FOLDER"
            sudo chmod u+x "$TARGET_FOLDER/admin/runAdmin.sh"
            sudo chmod u+x "$TARGET_FOLDER/backend/mvnw"
      - name: Create AdminPanel.properties for Admin Panel application
        env:
          ADMIN_PANEL_PROPERTIES: ${{ secrets.ADMIN_PANEL_PROPERTIES }}
          TARGET_FOLDER: ${{ secrets.TARGET_FOLDER }}
        run: |
            echo "$ADMIN_PANEL_PROPERTIES" > "$TARGET_FOLDER/admin/AdminPanel.properties"
      - name: Create secrets.properties for Spring Boot application
        env:
          SECRETS_PROPERTIES: ${{ secrets.SECRETS_PROPERTIES  }}
          TARGET_FOLDER: ${{ secrets.TARGET_FOLDER }}
        run: |
            echo "$SECRETS_PROPERTIES" > "$TARGET_FOLDER/backend/src/main/resources/secrets.properties"
      - name: Run unit tests
        env:
          TARGET_FOLDER: ${{ secrets.TARGET_FOLDER }}
        run: |
            cd "$TARGET_FOLDER/backend"
            sudo ./mvnw test
      - name: Shut down old version
        env:
          TARGET_FOLDER: ${{ secrets.TARGET_FOLDER }}
        run: |
            "$TARGET_FOLDER/admin/runAdmin.sh" << EOF > /dev/null
            9
            y

            10
            EOF
      - name: Run Spring Boot application
        env:
          TARGET_FOLDER: ${{ secrets.TARGET_FOLDER }}
          TARGET_LOG_FOLDER: ${{ secrets.TARGET_LOG_FOLDER }}
        run: |
            cd "$TARGET_FOLDER/backend"
            DATE=$(date "+%Y%m%d")
            sudo nohup ./mvnw spring-boot:run >> "$TARGET_LOG_FOLDER/spring-log_$DATE.txt" 2>&1 &
